---
title: "AWS Project Group 2"
output: html_notebook
---

```{r echo = TRUE}
# Date: 8/5/2019
# Author: Huy LE, Haodi Tu, Huibo Jia, Sourabh Gupta, Peter Broadstone
```


Clear environment of variables and packages  
=========================================

```{r message = FALSE, warning=FALSE}
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 
# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), detach, character.only = TRUE, unload = TRUE)

```

```{r}
# packages
library(tidyverse)
library(ggplot2)
library(gridExtra)
```

```{r}
# Load Data
adoption <- read.csv("adoption_final.csv")
april <- read.csv("april_billing_final.csv")
may <- read.csv("may_billing_final.csv")
june <- read.csv("june_billing_final.csv")
```


```{r}
summary(adoption)
summary(billing_april)
summary(billing_may)
summary(billing_june)

```

```{r}
# 
# adoption %>%
#   select(Customer_ID) %>%
#   distinct()

# 52,829 customers
```

```{r}
full_billing <- rbind(april, may)
full_billing <- rbind(full_billing, june)

full_billing <- full_billing %>%  mutate(month = as.character(format(as.Date(full_billing$Billing_month), '%m')))
# full_billing %>%
#   select(Customer_ID) %>%
#   distinct()
# 53,182 customers
  
adoption <- adoption %>% mutate(month = ifelse(Month == "April-19", "04",
                                               ifelse(Month == "May-19", "05",
                                                      ifelse(Month == "June-19", "06", 0))))
```

```{r}
full_dta <- left_join(full_billing, adoption, by = c("Customer_ID", "month") )
full_dta$Geo_Code <-  full_dta$Geo_Code %>% replace_na("Unknown")
full_dta$product_id <-  full_dta$product_id %>% replace_na("Unknown")
full_dta <-full_dta %>%  mutate(age_day = Sys.Date() - as.Date(full_dta$Registration_date))
full_dta <-full_dta %>%  mutate(age = age_day / 365,
                                        age_year = ifelse(age <= 1, 'within 1 year', 
                                                           ifelse(age >1 & age_day / 365 <= 3, '1-3 years',
                                                                   ifelse(age >3 & age_day / 365 <= 5, '3-5 years',
                                                                          ifelse(age > 5 & age_day / 365 <= 8, '5-8 years',
                                                                                 ifelse(age > 8, 'over 8 years', 0)))))) %>% select(-c(age_day, age))
  
```


```{r}
full_dta <- full_dta %>% mutate_if(is.character, as.factor)
```



```{r}
summary(full_dta)
```

+ missing values exist in adoption information after merging 

```{r}
# missing_adoption_customer <- full_dta[is.na(full_dta$Report),] %>%
#   summarise(bill = sum(Billed_amount),
#             count= n()) 

# remove missing adoption customers because their bill amount account for 1% of total bill amount -- they may be internal users

# No matter what aws product being used, the tools being used in that month is consistent?
full_dta <- full_dta[!is.na(full_dta$Month), ] %>%
  select(-Billing_month, -Registration_date, -Month, -product_id) %>%
  group_by(Customer_ID, month, Geo_Code, Visualize, Alert, Report, age_year, Customer_size) %>%
  summarise(monthly_bill = sum(Billed_amount))
summary(full_dta)

```


```{r}

full_dta <- full_dta %>% 
  mutate(tools_count = ifelse(Visualize=="Yes" & Alert == "No" & Report =="No", 1,
                              ifelse(Visualize=="Yes" & Alert == "Yes" & Report =="No",2,
                                     ifelse(Visualize=="Yes" & Alert == "No" & Report =="Yes",2,
                                      ifelse(Visualize=="Yes" & Alert == "Yes" & Report =="Yes",3,
                                              ifelse(Visualize=="No" & Alert == "Yes" & Report =="No",1,
                                                      ifelse(Visualize=="No" & Alert == "Yes" & Report =="Yes",2,
                                                              ifelse(Visualize=="No" & Alert == "No" & Report =="No",0,
                                                                     ifelse(Visualize=="No" & Alert == "No" & Report =="Yes",1,
                                                                            ifelse(Visualize=="No" & Alert == "Yes" & Report =="No",1))))))))))

  

write.csv(full_dta, file= "full_dta.csv")
```

Basic EDA
============================================

```{r}
full_dta <- read.csv("full_dta.csv")
str(full_dta)
```

```{r}
adoption_april <- filter(adoption, month== '04')
adoption_may <- filter(adoption, month== '05')
adoption_june <- filter(adoption, month== '06')
```

```{r}
df<-merge(x=adoption_april,y=adoption_may,by="Customer_ID") #43085
df2 <- merge(x=adoption_may,y=adoption_june,by="Customer_ID") #43893
growth_rate_may = (47272-43085)/45604
churn_rate_may = (45604 - 43085) /45604

growth_rate_june = (47149-43893)/47272
churn_rate_june = (47272 - 43893) /47272

```

```{r}
summary(full_dta)
cluster <- read.csv("AWSclusteredata.csv")

```

```{r}
cluster <- cluster %>%
  select(Customer_ID, CLUSTER) %>%
  group_by(Customer_ID) %>%
  distinct()
```

```{r}
df3 <- full_dta %>%
  select(Customer_ID, month, tools_count) %>%
  spread(key = month,
         value = tools_count,
         fill = 0,
         sep = "") %>%
  mutate(may_diff = month5-month4,
         june_diff = month6-month5) %>%
  mutate(may_diff = ifelse(may_diff < 0, -1,
                           ifelse(may_diff > 0, 1, 0))) %>%
  mutate(june_diff = ifelse(june_diff < 0, -1,
                           ifelse(june_diff > 0, 1, 0)))

df_may <- df3 %>%
   select(Customer_ID, may_diff) %>%
    spread(key = may_diff,
         value = may_diff,
         fill = 0,
         sep = "") 

df_june <- df3 %>%
   select(Customer_ID, june_diff) %>%
    spread(key = june_diff,
         value = june_diff,
         fill = 0,
         sep = "") 

df_diff <- df_may %>% 
  left_join(df_june, by = c("Customer_ID")) %>%
  select(-may_diff0, -june_diff0) %>%
  left_join(cluster, by = ("Customer_ID"))

write.csv(df_diff, file= "increase_decrease_cluster.csv")


df3 <- df3 %>% left_join(cluster, by = c("Customer_ID"))

  

df4 <- full_cluster %>%
  select(Customer_ID, month, CLUSTER) %>%
  spread(key = month,
         value = CLUSTER,
         sep = ".") 

```



```{r}
p1 <- ggplot(full_dta, aes(x=month)) + ggtitle("month") + xlab("month") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentage") + coord_flip() + theme_minimal()
p2 <- ggplot(full_dta, aes(x=Customer_size)) + ggtitle("Customer size") + xlab("Customer size") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentage") + coord_flip() + theme_minimal()
p3 <- ggplot(full_dta, aes(x=Geo_Code)) + ggtitle("Geo_Code") + xlab("Geo_Code") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentage") + coord_flip() + theme_minimal()
p4 <- ggplot(full_dta, aes(x=age_year)) + ggtitle("Customer Age") + xlab("Customer Age") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentage") + coord_flip() + theme_minimal()
grid.arrange(p1, p2, p3, p4, ncol=2)
```


```{r}
p5 <- ggplot(full_dta, aes(x=Visualize)) + ggtitle("Visualize") + xlab("Visualize") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentage") + coord_flip() + theme_minimal()
p6 <- ggplot(full_dta, aes(x=Alert)) + ggtitle("Alert") + xlab("Alert") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentage") + coord_flip() + theme_minimal()
p7 <- ggplot(full_dta, aes(x=Report)) + ggtitle("Report") + xlab("Report") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentage") + coord_flip() + theme_minimal()
grid.arrange(p5, p6, p7,ncol=2)
```






