---
title: "AWS Project Group 2"
output: html_notebook
---

```{r echo = TRUE}
# Date: 8/5/2019
# Author: Huy LE, Haodi Tu, Huibo Jia, Sourabh Gupta, Peter Broadstone
```

Clear environment of variables and packages  
=========================================

```{r message = FALSE, warning=FALSE}
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 
# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), detach, character.only = TRUE, unload = TRUE)
```

Load packages that include different functions  
=========================================

```{r message = FALSE, warning=FALSE}
# adding library
library(tidyverse)
library(GGally)
library(gridExtra)
library("readxl")
library(janitor)
library(stringr)
library(aod)
library(ggplot2)
library(stringi)
```

Load data 
=========================================

```{r message = FALSE, warning=FALSE}
#loading data
adoption <- read_csv('adoption_final.csv')
june <- read_csv('june_billing_final.csv')
may <- read_csv('may_billing_final.csv')
april <- read_csv('april_billing_final.csv')
```



Merge Data
=============================================
```{r}
full_billing <- rbind(april, may)
full_billing <- rbind(full_billing, june)

full_billing <- full_billing %>%  mutate(month = as.character(format(as.Date(full_billing$Billing_month), '%m')))
adoption <- adoption %>% mutate(month = ifelse(Month == "April-19", "04",
                                               ifelse(Month == "May-19", "05",
                                                      ifelse(Month == "June-19", "06", 0))))


full_dta <- left_join(full_billing, adoption, by = c("Customer_ID", "month") )

full_dta$Geo_Code <-  full_dta$Geo_Code %>% replace_na("Unknown")
full_dta$product_id <-  full_dta$product_id %>% replace_na(0)

full_dta <-full_dta %>%  mutate(age_day = Sys.Date() - full_dta$Registration_date)

full_dta <-full_dta %>%  mutate(age = as.numeric(round(age_day / 365,1)),
                                        age_year = ifelse(age <= 1, 'within 1 year', 
                                                           ifelse(age >1 & age_day / 365 <= 3, '1-3 years',
                                                                   ifelse(age >3 & age_day / 365 <= 5, '3-5 years',
                                                                          ifelse(age > 5 & age_day / 365 <= 8, '5-8 years',
                                                                                 ifelse(age > 8, 'over 8 years', 0)))))) %>% select(- c(age_day,Month,Billing_month))
  
#select(-c(age_day, age))
full_dta <- full_dta %>% mutate_if(is.character, as.factor)

# full_dta <- full_dta[!is.na(full_dta$Report),]


full_dta$Geo_Code %>% unique()
sapply(full_dta, function(x) sum(is.na(x))) 
summary(full_dta)
```

+ missing valvues exist in adoption infotion after merging 


Basic EDA
============================================
```{r}
full_dta[is.na(full_dta$Report),] %>% summary()

# assumption: those customers who has data in billing data but dose not have data in adoption does not use AWS cost management

```

# April 

```{r}
# missing customer adoption information 681 missing id
april_missing <- full_dta[full_dta$month == "04" & is.na(full_dta$Report),] 
april_missing %>% distinct()

# total billed amount from april missing  $340234.9
sum(april_missing$Billed_amount)

summary(april_missing)
```



```{r}
summary(april_missing)
# total bill amount by user age
april_missing %>% group_by(age_year) %>% 
  summarise(count = n(),
            total_bill = sum(Billed_amount))

# total bill amount by customer id
april_missing %>% group_by(Customer_ID) %>% 
  summarise(count = n(),
            total_bill = round(sum(Billed_amount),2)) %>% 
  arrange(desc(count))

```


```{r}
# remove na records
summary(april)
april <- april[!is.na(april$month), ]
# total bill amount by user age
# april %>% group_by(age_year) %>% 
#   summarise(count = n(),
#             total_bill = sum(Billed_amount))

# total bill amount by customer id
april %>% group_by(Geo_Code) %>% 
  summarise(count = n(),
            total_bill = round(sum(Billed_amount),2)) %>% 
  arrange(desc(count))

```

# May

```{r}
# missing customer adoption information 512 missing id
may_missing <- full_dta[full_dta$month == "05" & is.na(full_dta$Report),] 
may_missing %>% distinct()

# total billed amount from april missing  $230346.2
sum(may_missing$Billed_amount)

summary(may_missing)
```




# June 

```{r}
# missing customer adoption information 1251 missing id
june_missing <- full_dta[full_dta$month == "06" & is.na(full_dta$Report),] 
june_missing %>% distinct()

# total billed amount from april missing  $699478
sum(june_missing$Billed_amount)



summary(june_missing)
```

==================================================
```{r}
hfulldata <- full_dta %>% filter(!is.na(Report))
summary(hfulldata)
write.csv(MyData, file = "MyData.csv")


hfulldata %>%  gather(product, used, 8:10) %>%
                    ggplot(aes(x = month, fill = used))+
                    geom_bar(stat="count", position ="dodge") +
                    geom_text(stat='count', aes(label=..count..), vjust=1.5, colour="Black",position=position_dodge(.9), size=3) +
                    facet_grid(product~ Geo_Code)

```


Clustering
==================================================

```{r}
# removing NA values for clustering purpose
full_dta <- full_dta[!is.na(full_dta$Report),]
#full_dtaN <- scale(full_dta)
# install.packages("factoextra")
library(MASS)
#library(cluster)    # clustering algorithms

library(factoextra) # clustering algorithms & visualization
# data <- tibble::rowid_to_column(data, "ID")
clustering <- full_dta %>% tibble::rowid_to_column("ID") %>% 
                           mutate(
                                  Geo_Code_AMER = ifelse(full_dta$Geo_Code == "AMER", 1, 0),
                                  Geo_Code_APAC = ifelse(full_dta$Geo_Code == "APAC", 1, 0),
                                  Geo_Code_CHNA = ifelse(full_dta$Geo_Code == "CHNA", 1, 0),
                                  Geo_Code_EMEA = ifelse(full_dta$Geo_Code == "EMEA", 1, 0),
                                  Geo_Code_GEO_UNCLAIMED = ifelse(full_dta$Geo_Code == "GEO-UNCLAIMED", 1, 0),
                                  Geo_Code_GLBL = ifelse(full_dta$Geo_Code == "GLBL", 1, 0),
                                  Geo_Code_JAPN = ifelse(full_dta$Geo_Code == "JAPN", 1, 0),
                                  Geo_Code_Unknown = ifelse(full_dta$Geo_Code == "Unknown", 1, 0),
                                  Customer_size_Mid = ifelse(full_dta$Customer_size == "Mid", 1, 0),
                                  Customer_size_Large = ifelse(full_dta$Customer_size == "Large", 1, 0),
                                  Customer_size_Small = ifelse(full_dta$Customer_size == "Small", 1, 0),
                                  age_year_1 = ifelse(full_dta$age_year == "within 1 year", 1, 0),
                                  age_year_1_3 = ifelse(full_dta$age_year == "1-3 years", 1, 0),
                                  age_year_3_5 = ifelse(full_dta$age_year == "3-5 years", 1, 0),
                                  age_year_5_8 = ifelse(full_dta$age_year == "5-8 years", 1, 0),
                                  age_year_8 = ifelse(full_dta$age_year == "over 8 years", 1, 0),
                                  age = as.numeric(age)
                                  ) %>% 
                                  dplyr::select(-c(#Billing_month, 
                                                   Registration_date, 
                                                   #Month, 
                                                   month, Geo_Code, Customer_size, age_year,product_id, age
                                                   ))
clustering$Visualize <- ifelse(clustering$Visualize == "Yes", 1,0)
clustering$Alert <- ifelse(clustering$Alert == "Yes", 1,0)
clustering$Report <- ifelse(clustering$Report == "Yes", 1,0)

df <- clustering %>%
     remove_rownames() %>%
     column_to_rownames(var = 'ID') %>% dplyr::select(-Customer_ID, Billed_amount)

dfN <- scale(df)

# summary(dfN)

k6 <- kmeans(dfN, 6) #, nstart = 25

# ratio
bt6n <- k6$betweenss/k6$totss     
bt6n # 0.3013725, clusters are noise

#SSE
k6$tot.withinss

#fviz_cluster(k6, data = dfN)

#fviz_nbclust(dfN, kmeans, method = "wss")

# number of cluster
clusters6 <- k6$cluster
clusters6

#cluster size
clusterSizes6 <- k6$size
clusterSizes6

# assign cluster to data for trainng data mining model
full_dta_C <- cbind(full_dta, CNum=k6$cluster)
full_dta_C$age <- as.numeric(full_dta_C$age)
head(full_dta_C,10)

dfN_C <- cbind(dfN, CNum=k6$cluster)
## checking whether a customer was assigned in 2 different cluster
# full_dta_C %>% arrange(Customer_ID) %>% select(Customer_ID, CNum) %>% distinct() %>%
#               group_by(Customer_ID,CNum) %>%
#               summarise(count = n()) %>% filter(count>=2)
         
full_dta_C1 <- full_dta_C[full_dta_C$CNum == 1,]
head(full_dta_C1)
dim (full_dta_C1)
summary(full_dta_C1)

full_dta_C2 <- full_dta_C[full_dta_C$CNum == 2,]
head(full_dta_C2)
dim (full_dta_C2)
summary(full_dta_C2)

full_dta_C3 <- full_dta_C[full_dta_C$CNum == 3,]
head(full_dta_C3)
dim (full_dta_C3)
summary(full_dta_C3)

full_dta_C4 <- full_dta_C[full_dta_C$CNum == 4,]
head(full_dta_C4)
dim (full_dta_C4)
summary(full_dta_C4)

full_dta_C5 <- full_dta_C[full_dta_C$CNum == 5,]
head(full_dta_C5)
dim (full_dta_C5)
summary(full_dta_C5)

full_dta_C6 <- full_dta_C[full_dta_C$CNum == 6,]
head(full_dta_C6)
dim (full_dta_C6)
summary(full_dta_C6)

```

```{r}
set.seed(123)

# function to compute total within-cluster sum of square 
wss <- function(k) {
  kmeans(dfN, k, nstart = 10 )$tot.withinss
}

# Compute and plot wss for k = 1 to k = 15
k.values <- 1:10

# extract wss for 2-15 clusters
wss_values <- map_dbl(k.values, wss)

plot(k.values, wss_values,
       type="b", pch = 19, frame = FALSE, 
       xlab="Number of clusters K",
       ylab="Total within-clusters sum of squares")
```


```{r}
# new way for clustering
full_dta <- full_dta[!is.na(full_dta$Report),]
agrbilldata <-
agrbilldata <- full_billing %>% mutate(usedproduct = ifelse(is.na(product_id),0,1),
                                       age_day = Sys.Date() - Registration_date,
                                       age = round(as.numeric(age_day/365),1),
                                       age_year = ifelse(age <= 1, 'within 1 year', 
                                                           ifelse(age >1  & age <= 3, '1-3 years',
                                                                   ifelse(age >3 & age <= 5, '3-5 years',
                                                                          ifelse(age > 5 & age <= 8, '5-8 years','over 8 years'))))#,
                                       #billmonth = paste('bill',month, sep=''),
                                       #promonth = paste('pro',month, sep='')
                                       ) %>%
                                #select(-c(month)) %>%
                                group_by(Customer_ID, age, month, age_year) %>%
                                summarise(totalbillamt = sum(Billed_amount),
                                          NoProduct = sum(usedproduct))
                                # nest(totalbillamt, NoProduct, .key = 'value_col') %>%
                                # spread(key = month, value = value_col) %>%
                                # unnest(totalbillamt,NoProduct, .sep = '_')
  
agrbillamt <- agrbilldata %>% dplyr::select(Customer_ID,age,month,totalbillamt,age_year) %>%
                            spread(key = month, value = totalbillamt, fill =0)

agrbillamt
agrnoprod <-
agrnoprod <- agrbilldata %>% ungroup() %>%dplyr::select(Customer_ID, month, NoProduct, -age) %>%
                            spread(key = month, value = NoProduct, fill =0)
                                # tidyr::pivot_longer(-baker,
                                # names_to = c(".value", "order"),
                                # names_sep = "_")
colnames(agrnoprod) <- c("Customer_ID",'pro04','pro05', 'pro06')

agradopt <- adoption %>%
              mutate(Alert = ifelse(Alert == "Yes", 1,0),
                     Report = ifelse(Report == "Yes", 1,0),
                     Visualize = ifelse(Visualize == "Yes", 1,0),
                     Noservice = Alert +Report +Visualize,
                     servmonth = paste('serv',month, sep='')) %>%
              dplyr::select(-c(month, Month, Visualize, Report, Alert)) %>%
              spread(servmonth,Noservice, fill =0)

agradopt
sapply(agradopt, function(x) sum(is.na(x))) 

agrdata <- agrbillamt %>% merge(agrnoprod, by = 'Customer_ID') %>% left_join(agradopt, by ='Customer_ID' ) %>% distinct()

agrdata
agrdata$Geo_Code <-  agrdata$Geo_Code %>% replace_na("Unknown")

agrdata

sapply(agrdata, function(x) sum(is.na(x)))
agrdata<- agrdata %>% drop_na()
sapply(agrdata, function(x) sum(is.na(x)))
agrdata %>% arrange(Customer_ID)

```
Culstering 2nd time
=======================================
```{r}
Newclustering <- agrdata %>% tibble::rowid_to_column("ID") %>% 
                           mutate(
                             # Geo_Code_AMER = ifelse(Geo_Code == "AMER", 1, 0),
                             #      Geo_Code_APAC = ifelse(Geo_Code == "APAC", 1, 0),
                             #      Geo_Code_CHNA = ifelse(Geo_Code == "CHNA", 1, 0),
                             #      Geo_Code_EMEA = ifelse(Geo_Code == "EMEA", 1, 0),
                             #      Geo_Code_GEO_UNCLAIMED = ifelse(Geo_Code == "GEO-UNCLAIMED", 1, 0),
                             #      Geo_Code_GLBL = ifelse(Geo_Code == "GLBL", 1, 0),
                             #      Geo_Code_JAPN = ifelse(Geo_Code == "JAPN", 1, 0),
                             #      Geo_Code_Unknown = ifelse(Geo_Code == "Unknown", 1, 0),
                                  Customer_size_Mid = ifelse(Customer_size == "Mid", 1, 0),
                                  Customer_size_Large = ifelse(Customer_size == "Large", 1, 0),
                                  Customer_size_Small = ifelse(Customer_size == "Small", 1, 0),
                                  age_year_1 = ifelse(age_year == "within 1 year", 1, 0),
                                  age_year_1_3 = ifelse(age_year == "1-3 years", 1, 0),
                                  age_year_3_5 = ifelse(age_year == "3-5 years", 1, 0),
                                  age_year_5_8 = ifelse(age_year == "5-8 years", 1, 0),
                                  age_year_8 = ifelse(age_year == "over 8 years", 1, 0),
                                  age = as.numeric(age)
                                  ) %>% 
                                  dplyr::select(-c(Geo_Code, Customer_size, age_year))

df <- Newclustering %>%
     remove_rownames() %>%
     column_to_rownames(var = 'ID') %>% dplyr::select(-Customer_ID)

dfN <- scale(df)

summary(dfN)

k6 <- kmeans(dfN, 6) #, nstart = 25
attributes(k6)
#fviz_cluster(k6, data = dfN)

k2$betweenss # sum square of difference between overall mean and clustering mean
k6$tot.withinss
bt6n <- k6$betweenss/k6$totss   
bt6n
clusters6 <- k6$cluster
clusters6

clusterSizes6 <- k6$size
clusterSizes6

full_dta_C <- cbind(full_dta, CNum=k6$cluster)
full_dta_C$age <- as.numeric(full_dta_C$age)
head(full_dta_C,10)

```




Classification 
===============================

```{r}
# Training and validation sets
training <- full_dta[full_dta$month == "04" | full_dta$month == "05",]
validation <- full_dta[full_dta$month == "06",]

index <- sample(1:nrow(training), 3000, replace = TRUE)
training <- training[index,]


training <- training[!is.na(training$month), ]

training$Visualize <- ifelse(training$Visualize == "Yes", 1,0)
training$Alert <- ifelse(training$Alert == "Yes", 1,0)
training$Report <- ifelse(training$Report == "Yes", 1,0)

summary(training)


```


# Nerual Network
==========================================
```{r}
#library(neuralnet)
NNdata <- full_dta %>% tibble::rowid_to_column("ID") %>% 
                           mutate(
                                  Geo_Code_AMER = ifelse(full_dta$Geo_Code == "AMER", 1, 0),
                                  Geo_Code_APAC = ifelse(full_dta$Geo_Code == "APAC", 1, 0),
                                  Geo_Code_CHNA = ifelse(full_dta$Geo_Code == "CHNA", 1, 0),
                                  Geo_Code_EMEA = ifelse(full_dta$Geo_Code == "EMEA", 1, 0),
                                  Geo_Code_GEO_UNCLAIMED = ifelse(full_dta$Geo_Code == "GEO-UNCLAIMED", 1, 0),
                                  Geo_Code_GLBL = ifelse(full_dta$Geo_Code == "GLBL", 1, 0),
                                  Geo_Code_JAPN = ifelse(full_dta$Geo_Code == "JAPN", 1, 0),
                                  Geo_Code_Unknown = ifelse(full_dta$Geo_Code == "Unknown", 1, 0),
                                  Customer_size_Mid = ifelse(full_dta$Customer_size == "Mid", 1, 0),
                                  Customer_size_Large = ifelse(full_dta$Customer_size == "Large", 1, 0),
                                  Customer_size_Small = ifelse(full_dta$Customer_size == "Small", 1, 0),
                                  age_year_1 = ifelse(full_dta$age_year == "within 1 year", 1, 0),
                                  age_year_1_3 = ifelse(full_dta$age_year == "1-3 years", 1, 0),
                                  age_year_3_5 = ifelse(full_dta$age_year == "3-5 years", 1, 0),
                                  age_year_5_8 = ifelse(full_dta$age_year == "5-8 years", 1, 0),
                                  age_year_8 = ifelse(full_dta$age_year == "over 8 years", 1, 0),
                                  age = as.numeric(age)
                                  ) %>% 
                                  dplyr::select(-c(#Billing_month, 
                                                   Registration_date, 
                                                   #Month, 
                                                   #month, 
                                                   Geo_Code, Customer_size, age_year,product_id, age, Billed_amount
                                                   )) 
NNdata$Visualize <- ifelse(NNdata$Visualize == "Yes", 1,0)
NNdata$Alert <- ifelse(NNdata$Alert == "Yes", 1,0)
NNdata$Report <- ifelse(NNdata$Report == "Yes", 1,0)

NNdata_C <- cbind(NNdata, CNum=k6$cluster)


trainset <- NNdata_C %>% filter(month == '04' | month =='05') %>% dplyr::select(-month, -Customer_ID)
testset <- NNdata_C %>% filter(month == '06') %>% dplyr::select(-month, -Customer_ID)

# names of variables I don't want to scale
varnames <- c("Visualize", "Alert", "Report")

# index vector of columns which must not be scaled
index <- names(trainset) %in% varnames

# scale only the columns not in index
temp <- scale(trainset[, !index])

trainsetN <- scale(trainset[,!index])
trainsetN <- trainsetN %>% cbind(trainset[,index])

testsetN <- scale(testset[,!index])
testsetN <- testsetN%>% cbind(testset[,index])
summary(trainsetN)

```

### Alert 

```{r}
# Build a model without any hidden layer
index <- sample(1:nrow(trainsetN), 10000, replace = TRUE)
strainsetN <- trainsetN[index,]
stestN <- testsetN[index,]

Alertnm1 <- neuralnet(Visualize ~ Geo_Code_AMER+ 
                              Geo_Code_APAC+ 
                              Geo_Code_CHNA+ 
                              Geo_Code_EMEA+ 
                              Geo_Code_GEO_UNCLAIMED+ 
                              Geo_Code_GLBL+ 
                              Geo_Code_JAPN+ 
                              Geo_Code_Unknown+ 
                              Customer_size_Mid+ 
                              Customer_size_Large+ 
                              Customer_size_Small+ 
                              age_year_1+ 
                              age_year_1_3+ 
                              age_year_3_5+ 
                              age_year_5_8+ 
                              age_year_8 + 
                              CNum +
                              Alert +
                              Report, #+ age_year,# + Geo_Code + Customer_size,
  data=strainsetN, hidden = c(4,2))#,stepmax = 100000000)

plot(Alertnm1)

# Testing
alertpred1<- compute(Alertnm1, stestN[,c(2:18,20:211)])
head(alertpred1$net.result,5)
alertpred1
results <- data.frame(actual = stestN[,20], prediction = alertpred1$net.result)
head(results,5)

roundedresults<-sapply(results,round,digits=0)
roundedresultsdf=data.frame(roundedresults)
attach(roundedresultsdf)
table(actual,prediction)

summary(strain)

```